version: "3.8"

services:
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: testdb
    volumes:
      - echo-mysql-data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  echo-mysql-data:
